apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-lab-v8
  region: eu-west-1
  version: "1.27"

managedNodeGroups:
  - name: gn-one
    instanceType: t2.medium
    desiredCapacity: 2
    volumeSize: 20