apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  labels:
    app: wordpress
spec:
  storageClassName: pv-wordpress
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi